# thymeleaf settings
spring.thymeleaf.cache: false

# h2 database settings
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./db/horseshoedb
    username: horseshoeb
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console